Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"

    # Network configurations
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", host: 80, guest: 8080

    # Sync folder with project
    config.vm.synced_folder "../", "/vagrant"
    
    # Configure VM
    config.vm.provider "virtualbox" do |vm|
        vm.name = "project_site"
        vm.cpus = 2
        vm.memory = 1024
    end

    # Provision VM with Ansible
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "/vagrant/ansible/deploy.yml"
        ansible.inventory_path = "/vagrant/ansible/inventory"
        ansible.compatibility_mode = "2.0"
    end
end 