---
- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Packages
  ansible.builtin.apt:
    name: 
      - terraform
      - docker.io
    state: present

- name: Synchronize Terraform files to localhost
  ansible.builtin.synchronize:
    mode: push
    src: /home/asus/actions-runner_1/_work/home_site_deploy/home_site_deploy/terraform/
    dest: "{{ terraform_directory }}"
    rsync_opts:
      - "--chmod=0644"

- name: Synchronize scripts from pihole to localhost
  ansible.builtin.synchronize:
    mode: push
    src: /home/asus/actions-runner_1/_work/home_site_deploy/home_site_deploy/scripts/
    dest: "{{ terraform_directory }}"
    rsync_opts:
      - "--chmod=0644"

- name: Terraform Init
  ansible.builtin.shell: terraform init
  args:
    chdir: "{{ terraform_directory }}/terraform"
  register: terraform_init
  failed_when: terraform_init.rc != 0

- name: Terraform Plan
  ansible.builtin.shell: terraform plan -var "git_token={{ git_token }}" -var "pihole_web_password={{ pihole_web_password }}"
  args:
    chdir: "{{ terraform_directory }}/terraform"
  register: terraform_plan
  failed_when: terraform_plan.rc != 0

- name: Terraform Apply
  ansible.builtin.shell: terraform apply -var "git_token={{ git_token }}" -var "pihole_web_password={{ pihole_web_password }}" -auto-approve
  args:
    chdir: "{{ terraform_directory }}/terraform"
  async: 600
  poll: 0
  register: terraform_apply

- name: Wait for Terraform Apply to finish
  ansible.builtin.async_status:
    jid: "{{ terraform_apply.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 10