---
- name: Deploy Terraform
  hosts: localhost
  gather_facts: true
  become: true
  become_user: root
  vars:
    terraform_directory: "/opt/terraform"

  roles:
    - vpn_setup
    - terraform_setup
    - pihole_setup
