---
- name: Deploy Terraform
  hosts: localhost
  gather_facts: yes
  become: true
  become_user: root
  vars:
    terraform_directory: "/opt/terraform"
    git_token: "{{ git_token }}"

  tasks:
    - name: Add secrets to vpn configuration
      lineinfile: 
        path: "/opt/vpn_secrets.conf"
        line: "{{ item.line }}"
        state: present
        create: true
      with_items:
        - { line: "vpn.secrets.Xauth password:{{ vpn_password }}" }
        - { line: "vpn.secrets.preshared-key:{{ vpn_psk }}" }

    - name: Check if VPN is already connected
      command: nmcli con show --active | grep -q "VPN 1"
      register: vpn_status
      ignore_errors: true
      failed_when: false

    - name: Connect to VPN if not already connected
      command: nmcli con up "VPN 1" passwd-file /opt/vpn_secrets.conf
      when: vpn_status.rc != 0

    - name: Add HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Packages
      ansible.builtin.apt:
        name: 
          - terraform
          - docker.io
        state: present

    - name: Copy Terraform files to localhost
      ansible.builtin.copy:
        src: /home/asus/actions-runner_1/_work/home_site_deploy/home_site_deploy/terraform
        dest: "{{ terraform_directory }}"
        mode: '0644'

    - name: Copy scripts from pihole to localhost
      ansible.builtin.copy:
        src: /home/asus/actions-runner_1/_work/home_site_deploy/home_site_deploy/scripts
        dest: "{{ terraform_directory }}"
        mode: '0644'

    - name: Terraform Init
      command: terraform init
      args:
        chdir: "{{ terraform_directory }}/terraform"

    - name: Terraform Plan
      command: terraform plan -var "git_token={{ git_token }}"
      args:
        chdir: "{{ terraform_directory }}/terraform"

    - name: Terraform Apply
      command: terraform apply -var "git_token={{ git_token }}" -auto-approve
      args:
        chdir: "{{ terraform_directory }}/terraform"
      async: 60

    - name: Make scripts executable in docker
      community.docker.docker_container_exec:
        container: pihole
        command: chmod +x 10-adlists.sh
        chdir: /etc/cont-init.d
      retries: 3
      delay: 5

    - name: Make gravity.sh executable
      ansible.builtin.file:
        path: "{{ terraform_directory }}/scripts/gravity.sh"
        mode: '0755'

    - name: Add "pihole update gravity" script to cron
      cron:
        name: "pihole-update-gravity"
        user: root
        minute: "0"
        hour: "0"
        job: "{{ terraform_directory }}/scripts/gravity.sh"
    
    - name: Ensure /var/log/pihole directory exists
      ansible.builtin.file:
        path: /var/log/pihole
        state: directory
        owner: root
        group: root
        mode: '0755'
