---
- name: Deploy Terraform
  hosts: localhost
  gather_facts: yes
  become: true
  become_user: root
  vars:
    terraform_directory: "/opt/terraform"
    git_token: "{{ lookup('env', 'TERRAFORM_TOKEN') }}"

  tasks:
    - name: Add HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present

    - name: Copy Terraform files to localhost
      ansible.builtin.copy:
        src: /home/asus/actions-runner_1/_work/home_site_deploy/home_site_deploy/terraform
        dest: "{{ terraform_directory }}"
        mode: '0644'

    - name: Initialize Terraform
      community.general.terraform:
        project_path: "{{ terraform_directory }}/terraform"
        force_init: true
        backend_config:
          bucket: terraform-state
          key: terraform.tfstate
          region: us-east-1
