name: Deploy project

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Linting Terraform  
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      
      - name: Run TFLint
        run: tflint
        working-directory: terraform

  configure_and_deploy:
    runs-on: self-hosted
    needs: lint
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible if not already installed
        run: |
          if ! ansible --version &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y ansible
          else
            echo "Ansible is already installed"
          fi

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: |
            [Production]
            localhost ansible_connection=local
          options: >
            --extra-vars "git_token=${{ secrets.TERRAFORM_TOKEN }} vpn_password=${{ secrets.VPN_PASSWORD }} vpn_psk=${{ secrets.VPN_PSK }} pihole_web_password=${{ secrets.PIHOLE_WEB_PASSWORD }}"
