name: Deploy project

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint terraform
        run: echo "Lint terraform plan"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Linting terraform  
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      
      - name: Run TFLint
        run: tflint
        working-directory: terraform

  deploy:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Deploy project
        run: echo "Deploying project"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ansible
          inventory: |
            [Production]
            localhost ansible_connection=local
          options:
            --extra-vars "git_token=${{ secrets.TERRAFORM_TOKEN }}"
